
#region Copyright (c) 2015 KEngine / Kelly <http://github.com/mr-kelly>, All rights reserved.

// KEngine - Asset Bundle framework for Unity3D
// ===================================
// 
// Author:  Kelly
// Email: 23110388@qq.com
// Github: https://github.com/mr-kelly/KEngine
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3.0 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library.

#endregion

// This file is auto generated by KSettingModuleEditor.cs!
// Don't manipulate me!

using System.Collections;
using System.Collections.Generic;
using CosmosTable;
using KEngine;
using KEngine.Modules;
namespace AppSettings
{
	/// <summary>
    /// All settings list here, so you can reload all settings manully from the list.
	/// </summary>
    public class SettingsDefine
    {
        private static IReloadableSettings[] _settingsList;
        public static IReloadableSettings[] SettingsList
        {
            get
            {
                if (_settingsList == null)
                {
                    _settingsList = new IReloadableSettings[]
                    { 
                        ExampleSettings.GetInstance(),
                        SubdirExample2Settings.GetInstance(),
                        SubdirSettings.GetInstance(),
                        SubdirSubSubDirExample3Settings.GetInstance(),
                    };
                }
                return _settingsList;
            }
        }
    }


	/// <summary>
	/// Auto Generate for Tab File: Example.bytes
    /// No use of generic and reflection, for better performance,  less IL code generating
	/// </summary>>
    public partial class ExampleSettings : IReloadableSettings
    {
		public static readonly string TabFilePath = "Example.bytes";
        static readonly ExampleSettings _instance = new ExampleSettings();
        Dictionary<string, ExampleSetting> _dict = new Dictionary<string, ExampleSetting>();

        /// <summary>
        /// Trigger delegate when reload the Settings
        /// </summary>>
	    public static System.Action OnReload;

        /// <summary>
        /// Constructor, just reload(init)
        /// When Unity Editor mode, will watch the file modification and auto reload
        /// </summary>
	    private ExampleSettings()
	    {
            ReloadAll();
#if UNITY_EDITOR
	        if (SettingModule.IsFileSystemMode)
	        {
	            SettingModule.WatchSetting(TabFilePath, (path) =>
	            {
	                if (path.Replace("\\", "/").EndsWith(path))
	                {
                        ReloadAll();
	                    KLogger.LogConsole_MultiThread("Reload success! -> " + path);
	                }
	            });
	        }
#endif
        }

        /// <summary>
        /// Get the singleton
        /// </summary>
        /// <returns></returns>
	    public static ExampleSettings GetInstance()
	    {
	        return _instance;
	    }

        /// <summary>
        /// Do reload the setting file
        /// </summary>
	    public void ReloadAll()
        {
	        using (var tableFile = SettingModule.Get(TabFilePath))
	        {
	            foreach (var row in tableFile)
	            {
                    var pk = ExampleSetting.ParsePrimaryKey(row);
                    ExampleSetting setting;
                    if (!_dict.TryGetValue(pk, out setting))
                    {
                        setting = new ExampleSetting(row);
                        _dict[setting.Id] = setting;
                    }
                    else setting.Reload(row);
	            }
	            
	        }
	        if (OnReload != null)
	        {
	            OnReload();
	        }
        }
	    
        public static IEnumerable GetAll()
        {
            foreach (var row in _instance._dict.Values)
            {
                yield return row;
            }
        }
        
        public static ExampleSetting GetByPrimaryKey(string primaryKey)
        {
            ExampleSetting setting;
            if (_instance._dict.TryGetValue(primaryKey, out setting)) return setting;
            return null;
        }
    }

	/// <summary>
	/// Auto Generate for Tab File: Example.bytes
    /// Singleton class for less memory use
	/// </summary>
	public partial class ExampleSetting : TableRowParser
	{
		
        /// <summary>
        /// ID Column/编号/主键
        /// </summary>
        public string Id { get; private set;}
        
        /// <summary>
        /// Name/名字
        /// </summary>
        public string Name { get; private set;}
        
        /// <summary>
        /// 用于组合成Id主键
        /// </summary>
        public string KeyString { get; private set;}
        
        /// <summary>
        /// 数据测试
        /// </summary>
        public int Number { get; private set;}
        
        /// <summary>
        /// ArrayTest/测试数组
        /// </summary>
        public string[] StrArray { get; private set;}
        
        /// <summary>
        /// 字典测试
        /// </summary>
        public Dictionary<string,int> StrIntMap { get; private set;}
        

        internal ExampleSetting(TableRow row)
        {
            Reload(row);
        }

        internal void Reload(TableRow row)
        { 
            Id = row.Get_string(row.Values[0], ""); 
            Name = row.Get_string(row.Values[1], ""); 
            KeyString = row.Get_string(row.Values[2], ""); 
            Number = row.Get_int(row.Values[3], ""); 
            StrArray = row.Get_string_array(row.Values[4], ""); 
            StrIntMap = row.Get_Dictionary_string_int(row.Values[5], ""); 
        }

        /// <summary>
        /// Get PrimaryKey from a table row
        /// </summary>
        /// <param name="row"></param>
        /// <returns></returns>
        public static string ParsePrimaryKey(TableRow row)
        {
            var primaryKey = row.Get_string(row.Values[0], "");
            return primaryKey;
        }
	}

	/// <summary>
	/// Auto Generate for Tab File: Subdir/Example2.bytes
    /// No use of generic and reflection, for better performance,  less IL code generating
	/// </summary>>
    public partial class SubdirExample2Settings : IReloadableSettings
    {
		public static readonly string TabFilePath = "Subdir/Example2.bytes";
        static readonly SubdirExample2Settings _instance = new SubdirExample2Settings();
        Dictionary<int, SubdirExample2Setting> _dict = new Dictionary<int, SubdirExample2Setting>();

        /// <summary>
        /// Trigger delegate when reload the Settings
        /// </summary>>
	    public static System.Action OnReload;

        /// <summary>
        /// Constructor, just reload(init)
        /// When Unity Editor mode, will watch the file modification and auto reload
        /// </summary>
	    private SubdirExample2Settings()
	    {
            ReloadAll();
#if UNITY_EDITOR
	        if (SettingModule.IsFileSystemMode)
	        {
	            SettingModule.WatchSetting(TabFilePath, (path) =>
	            {
	                if (path.Replace("\\", "/").EndsWith(path))
	                {
                        ReloadAll();
	                    KLogger.LogConsole_MultiThread("Reload success! -> " + path);
	                }
	            });
	        }
#endif
        }

        /// <summary>
        /// Get the singleton
        /// </summary>
        /// <returns></returns>
	    public static SubdirExample2Settings GetInstance()
	    {
	        return _instance;
	    }

        /// <summary>
        /// Do reload the setting file
        /// </summary>
	    public void ReloadAll()
        {
	        using (var tableFile = SettingModule.Get(TabFilePath))
	        {
	            foreach (var row in tableFile)
	            {
                    var pk = SubdirExample2Setting.ParsePrimaryKey(row);
                    SubdirExample2Setting setting;
                    if (!_dict.TryGetValue(pk, out setting))
                    {
                        setting = new SubdirExample2Setting(row);
                        _dict[setting.Id] = setting;
                    }
                    else setting.Reload(row);
	            }
	            
	        }
	        if (OnReload != null)
	        {
	            OnReload();
	        }
        }
	    
        public static IEnumerable GetAll()
        {
            foreach (var row in _instance._dict.Values)
            {
                yield return row;
            }
        }
        
        public static SubdirExample2Setting GetByPrimaryKey(int primaryKey)
        {
            SubdirExample2Setting setting;
            if (_instance._dict.TryGetValue(primaryKey, out setting)) return setting;
            return null;
        }
    }

	/// <summary>
	/// Auto Generate for Tab File: Subdir/Example2.bytes
    /// Singleton class for less memory use
	/// </summary>
	public partial class SubdirExample2Setting : TableRowParser
	{
		
        /// <summary>
        /// ID Column/编号/主键
        /// </summary>
        public int Id { get; private set;}
        
        /// <summary>
        /// Name/名字
        /// </summary>
        public string Name { get; private set;}
        

        internal SubdirExample2Setting(TableRow row)
        {
            Reload(row);
        }

        internal void Reload(TableRow row)
        { 
            Id = row.Get_int(row.Values[0], ""); 
            Name = row.Get_string(row.Values[1], ""); 
        }

        /// <summary>
        /// Get PrimaryKey from a table row
        /// </summary>
        /// <param name="row"></param>
        /// <returns></returns>
        public static int ParsePrimaryKey(TableRow row)
        {
            var primaryKey = row.Get_int(row.Values[0], "");
            return primaryKey;
        }
	}

	/// <summary>
	/// Auto Generate for Tab File: Subdir/__.bytes
    /// No use of generic and reflection, for better performance,  less IL code generating
	/// </summary>>
    public partial class SubdirSettings : IReloadableSettings
    {
		public static readonly string TabFilePath = "Subdir/__.bytes";
        static readonly SubdirSettings _instance = new SubdirSettings();
        Dictionary<string, SubdirSetting> _dict = new Dictionary<string, SubdirSetting>();

        /// <summary>
        /// Trigger delegate when reload the Settings
        /// </summary>>
	    public static System.Action OnReload;

        /// <summary>
        /// Constructor, just reload(init)
        /// When Unity Editor mode, will watch the file modification and auto reload
        /// </summary>
	    private SubdirSettings()
	    {
            ReloadAll();
#if UNITY_EDITOR
	        if (SettingModule.IsFileSystemMode)
	        {
	            SettingModule.WatchSetting(TabFilePath, (path) =>
	            {
	                if (path.Replace("\\", "/").EndsWith(path))
	                {
                        ReloadAll();
	                    KLogger.LogConsole_MultiThread("Reload success! -> " + path);
	                }
	            });
	        }
#endif
        }

        /// <summary>
        /// Get the singleton
        /// </summary>
        /// <returns></returns>
	    public static SubdirSettings GetInstance()
	    {
	        return _instance;
	    }

        /// <summary>
        /// Do reload the setting file
        /// </summary>
	    public void ReloadAll()
        {
	        using (var tableFile = SettingModule.Get(TabFilePath))
	        {
	            foreach (var row in tableFile)
	            {
                    var pk = SubdirSetting.ParsePrimaryKey(row);
                    SubdirSetting setting;
                    if (!_dict.TryGetValue(pk, out setting))
                    {
                        setting = new SubdirSetting(row);
                        _dict[setting.Id] = setting;
                    }
                    else setting.Reload(row);
	            }
	            
	        }
	        if (OnReload != null)
	        {
	            OnReload();
	        }
        }
	    
        public static IEnumerable GetAll()
        {
            foreach (var row in _instance._dict.Values)
            {
                yield return row;
            }
        }
        
        public static SubdirSetting GetByPrimaryKey(string primaryKey)
        {
            SubdirSetting setting;
            if (_instance._dict.TryGetValue(primaryKey, out setting)) return setting;
            return null;
        }
    }

	/// <summary>
	/// Auto Generate for Tab File: Subdir/__.bytes
    /// Singleton class for less memory use
	/// </summary>
	public partial class SubdirSetting : TableRowParser
	{
		
        /// <summary>
        /// ID Column/编号/主键
        /// </summary>
        public string Id { get; private set;}
        
        /// <summary>
        /// Name/名字
        /// </summary>
        public string Name { get; private set;}
        

        internal SubdirSetting(TableRow row)
        {
            Reload(row);
        }

        internal void Reload(TableRow row)
        { 
            Id = row.Get_string(row.Values[0], ""); 
            Name = row.Get_string(row.Values[1], ""); 
        }

        /// <summary>
        /// Get PrimaryKey from a table row
        /// </summary>
        /// <param name="row"></param>
        /// <returns></returns>
        public static string ParsePrimaryKey(TableRow row)
        {
            var primaryKey = row.Get_string(row.Values[0], "");
            return primaryKey;
        }
	}

	/// <summary>
	/// Auto Generate for Tab File: Subdir/SubSubDir/Example3.bytes
    /// No use of generic and reflection, for better performance,  less IL code generating
	/// </summary>>
    public partial class SubdirSubSubDirExample3Settings : IReloadableSettings
    {
		public static readonly string TabFilePath = "Subdir/SubSubDir/Example3.bytes";
        static readonly SubdirSubSubDirExample3Settings _instance = new SubdirSubSubDirExample3Settings();
        Dictionary<string, SubdirSubSubDirExample3Setting> _dict = new Dictionary<string, SubdirSubSubDirExample3Setting>();

        /// <summary>
        /// Trigger delegate when reload the Settings
        /// </summary>>
	    public static System.Action OnReload;

        /// <summary>
        /// Constructor, just reload(init)
        /// When Unity Editor mode, will watch the file modification and auto reload
        /// </summary>
	    private SubdirSubSubDirExample3Settings()
	    {
            ReloadAll();
#if UNITY_EDITOR
	        if (SettingModule.IsFileSystemMode)
	        {
	            SettingModule.WatchSetting(TabFilePath, (path) =>
	            {
	                if (path.Replace("\\", "/").EndsWith(path))
	                {
                        ReloadAll();
	                    KLogger.LogConsole_MultiThread("Reload success! -> " + path);
	                }
	            });
	        }
#endif
        }

        /// <summary>
        /// Get the singleton
        /// </summary>
        /// <returns></returns>
	    public static SubdirSubSubDirExample3Settings GetInstance()
	    {
	        return _instance;
	    }

        /// <summary>
        /// Do reload the setting file
        /// </summary>
	    public void ReloadAll()
        {
	        using (var tableFile = SettingModule.Get(TabFilePath))
	        {
	            foreach (var row in tableFile)
	            {
                    var pk = SubdirSubSubDirExample3Setting.ParsePrimaryKey(row);
                    SubdirSubSubDirExample3Setting setting;
                    if (!_dict.TryGetValue(pk, out setting))
                    {
                        setting = new SubdirSubSubDirExample3Setting(row);
                        _dict[setting.Id] = setting;
                    }
                    else setting.Reload(row);
	            }
	            
	        }
	        if (OnReload != null)
	        {
	            OnReload();
	        }
        }
	    
        public static IEnumerable GetAll()
        {
            foreach (var row in _instance._dict.Values)
            {
                yield return row;
            }
        }
        
        public static SubdirSubSubDirExample3Setting GetByPrimaryKey(string primaryKey)
        {
            SubdirSubSubDirExample3Setting setting;
            if (_instance._dict.TryGetValue(primaryKey, out setting)) return setting;
            return null;
        }
    }

	/// <summary>
	/// Auto Generate for Tab File: Subdir/SubSubDir/Example3.bytes
    /// Singleton class for less memory use
	/// </summary>
	public partial class SubdirSubSubDirExample3Setting : TableRowParser
	{
		
        /// <summary>
        /// ID Column/编号/主键
        /// </summary>
        public string Id { get; private set;}
        
        /// <summary>
        /// Name/名字
        /// </summary>
        public string Name { get; private set;}
        

        internal SubdirSubSubDirExample3Setting(TableRow row)
        {
            Reload(row);
        }

        internal void Reload(TableRow row)
        { 
            Id = row.Get_string(row.Values[0], ""); 
            Name = row.Get_string(row.Values[1], ""); 
        }

        /// <summary>
        /// Get PrimaryKey from a table row
        /// </summary>
        /// <param name="row"></param>
        /// <returns></returns>
        public static string ParsePrimaryKey(TableRow row)
        {
            var primaryKey = row.Get_string(row.Values[0], "");
            return primaryKey;
        }
	}
 
}
